# Generated by Django 3.2.6 on 2021-11-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_dethi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ChucVuCaNhan',
            field=models.IntegerField(choices=[(0, 'Phu Huynh'), (1, 'Hoc Sinh'), (2, 'Sinh Vien'), (3, 'Giáo Viên - Giảng Viên')], default=0),
        ),
    ]
