# Generated by Django 3.2.6 on 2021-11-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_user_chucvucanhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dethi',
            name='HinhThucDe',
            field=models.IntegerField(choices=[(0, 'Luyện tập trắc nghiệm'), (1, 'Đề thi thông min'), (2, 'Lý thuyết tương tác'), (3, 'Hỏi và Đáp'), (4, 'Đề thi Tự luận, chấm điểm trực tiếp lên bài'), (5, 'Đề thi tắc nghệm từ file PDF hoặc Word'), (6, 'Đề thi trắc nghiệm từ ma trận')], default=0),
        ),
        migrations.AlterField(
            model_name='dethi',
            name='Lop',
            field=models.IntegerField(choices=[(0, 'Mẫu giáo'), (1, 'Lớp 1'), (2, 'Lớp 2'), (3, 'Lớp 3'), (4, 'Lớp 4'), (5, 'Lớp 5'), (6, 'Lớp 6'), (7, 'Lớp 7'), (8, 'Lớp 8'), (9, 'Lớp 9'), (10, 'Lớp 10'), (11, 'Lớp 11'), (12, 'Lớp 12'), (13, 'Đại học')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ChucVuCaNhan',
            field=models.IntegerField(choices=[(0, 'Phụ Huynh'), (1, 'Học Sinh'), (2, 'Sinh Viên'), (3, 'Giáo Viên - Giảng Viên')], default=0),
        ),
    ]
