# Generated by Django 3.2.6 on 2021-11-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20211110_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaMon', models.CharField(max_length=50)),
                ('TenMon', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dethi',
            name='HinhThucDe',
            field=models.IntegerField(choices=[(0, 'Luyện tập trắc nghiệm'), (1, 'Đề thi thông minh'), (2, 'Lý thuyết tương tác'), (3, 'Hỏi và Đáp'), (4, 'Đề thi Tự luận, chấm điểm trực tiếp lên bài'), (5, 'Đề thi tắc nghệm từ file PDF hoặc Word'), (6, 'Đề thi trắc nghiệm từ ma trận')], default=0),
        ),
        migrations.CreateModel(
            name='De',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.dethi')),
            ],
        ),
        migrations.AddField(
            model_name='dethi',
            name='TenMonThi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.monthi'),
        ),
    ]
