# Generated by Django 3.2.6 on 2021-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20211122_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ChucVu',
            field=models.IntegerField(choices=[(0, 'Phụ Huynh'), (1, 'Học Sinh'), (2, 'Sinh Viên'), (3, 'Giáo Viên - Giảng Viên')], default=0),
        ),
    ]
