# Generated by Django 3.2.6 on 2021-11-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_monhoc_tenmonhoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monhoc',
            name='GhiChu',
        ),
    ]
